# Generated by Django 6.0.6 on 2026-06-25 20:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('stocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=25, unique=True)),
                ('type_document', models.CharField(choices=[('vente', 'Vente directe'), ('devis', 'Devis / Proforma'), ('bon_livraison', 'Bon de livraison')], default='vente', max_length=20)),
                ('statut', models.CharField(choices=[('brouillon', '📝 Brouillon'), ('finalisee', '✅ Finalisée'), ('annulee', '❌ Annulée')], default='brouillon', max_length=15)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('sous_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remise_pourcentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('remise_montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_paye', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='patients.patient')),
                ('vendeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_article', models.CharField(choices=[('monture', 'Monture'), ('verre_od', 'Verre OD'), ('verre_og', 'Verre OG'), ('lentille', 'Lentille'), ('accessoire', 'Accessoire'), ('service', 'Prestation / Service'), ('autre', 'Autre')], max_length=15)),
                ('designation', models.CharField(max_length=300)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('quantite', models.IntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('accessoire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.accessoire')),
                ('lentille', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.lentille')),
                ('monture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.monture')),
                ('verre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.verre')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='ventes.vente')),
            ],
            options={
                'verbose_name': 'Ligne de vente',
                'verbose_name_plural': 'Lignes de vente',
            },
        ),
        migrations.CreateModel(
            name='Encaissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('especes', '💵 Espèces'), ('cib', '💳 CIB / Edahabia'), ('cheque', '📄 Chèque'), ('virement', '🏦 Virement'), ('autre', 'Autre')], max_length=15)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='N° chèque / référence')),
                ('est_acompte', models.BooleanField(default=False, verbose_name='Acompte')),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encaissements', to='ventes.vente')),
            ],
            options={
                'verbose_name': 'Encaissement',
                'verbose_name_plural': 'Encaissements',
            },
        ),
    ]
