# Generated by Django 5.2.9 on 2026-06-30 00:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('categorie', models.CharField(choices=[('Loyer', 'Loyer'), ('Électricité', 'Électricité / Gaz'), ('Eau', 'Eau'), ('Internet', 'Internet / Téléphone'), ('Fourniture', 'Fourniture de bureau'), ('Salaire', 'Salaires'), ('Maintenance', 'Entretien / Maintenance'), ('Autre', 'Autre')], default='Autre', max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type_charge', models.CharField(choices=[('Fixe', 'Fixe'), ('Variable', 'Variable')], default='Variable', max_length=20)),
                ('statut', models.CharField(choices=[('Payé', 'Payé'), ('En attente', 'En attente')], default='Payé', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Charge / Dépense',
                'verbose_name_plural': 'Charges / Dépenses',
                'ordering': ['-date'],
            },
        ),
    ]
