# Generated by Django 6.0.6 on 2026-06-25 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('ventes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_canal', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], default='sms', max_length=10)),
                ('categorie', models.CharField(choices=[('rappel_visite', 'Rappel de visite'), ('promo', 'Promotion / Offre'), ('anniversaire', 'Anniversaire'), ('pret_commande', 'Commande prête'), ('fidelite', 'Programme fidélité'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('contenu', models.TextField(verbose_name='Contenu du message (variables: {{patient_nom}}, {{date_rappel}}, {{points}})')),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Modèle de message',
                'verbose_name_plural': 'Modèles de messages',
            },
        ),
        migrations.CreateModel(
            name='ProgrammeFidelite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Programme Fidélité Optuce', max_length=100)),
                ('points_par_dinar', models.DecimalField(decimal_places=3, default=0.01, max_digits=5, verbose_name='Points par dinar dépensé')),
                ('valeur_point_da', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name="Valeur d'un point (DA)")),
                ('seuil_remise_familiale', models.IntegerField(default=3, verbose_name='Nb membres famille pour remise')),
                ('taux_remise_familiale', models.DecimalField(decimal_places=1, default=5, max_digits=4, verbose_name='Taux remise familiale (%)')),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Programme de fidélité',
            },
        ),
        migrations.CreateModel(
            name='CompteFidelite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_cumules', models.IntegerField(default=0)),
                ('points_utilises', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compte_fidelite', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Compte fidélité',
            },
        ),
        migrations.CreateModel(
            name='GroupeFamilial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de famille / Groupe')),
                ('taux_remise', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Remise familiale (%)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('membres', models.ManyToManyField(blank=True, related_name='groupes_familiaux', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Groupe familial',
                'verbose_name_plural': 'Groupes familiaux',
            },
        ),
        migrations.CreateModel(
            name='MessageEnvoye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(max_length=10)),
                ('numero_destinataire', models.CharField(max_length=20)),
                ('contenu', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('envoye', 'Envoyé'), ('livre', 'Livré'), ('echec', "Échec d'envoi")], default='en_attente', max_length=15)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('reponse_api', models.TextField(blank=True, verbose_name='Réponse API')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to='patients.patient')),
                ('modele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.modelemessage')),
            ],
            options={
                'verbose_name': 'Message envoyé',
                'verbose_name_plural': 'Messages envoyés',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Rappel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rappel', models.CharField(choices=[('controle_vue', '👁 Contrôle de vue (2 ans)'), ('renouvellement_lentilles', '🔵 Renouvellement lentilles'), ('expiration_chifa', '🏥 Expiration carte Chifa'), ('anniversaire', '🎂 Anniversaire'), ('personnalise', '📋 Rappel personnalisé')], max_length=30)),
                ('statut', models.CharField(choices=[('programme', 'Programmé'), ('envoye', 'Envoyé'), ('annule', 'Annulé'), ('reporte', 'Reporté')], default='programme', max_length=15)),
                ('date_prevue', models.DateField()),
                ('canal', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], default='sms', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('message_envoye', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.messageenvoye')),
                ('modele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.modelemessage')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rappels', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Rappel',
                'verbose_name_plural': 'Rappels',
                'ordering': ['date_prevue'],
            },
        ),
        migrations.CreateModel(
            name='TransactionFidelite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('gain', '+ Gain suite à achat'), ('utilisation', '- Utilisation'), ('bonus', '+ Bonus offert'), ('expiration', '- Expiration'), ('correction', '± Correction manuelle')], max_length=20)),
                ('points', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='crm.comptefidelite')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventes.vente')),
            ],
            options={
                'verbose_name': 'Transaction fidélité',
                'ordering': ['-date'],
            },
        ),
    ]
