# Generated by Django 6.0.6 on 2026-06-25 20:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('medecin', models.CharField(max_length=150, verbose_name='Médecin prescripteur')),
                ('specialite', models.CharField(blank=True, max_length=100, verbose_name='Spécialité')),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ordonnance',
                'verbose_name_plural': 'Ordonnances',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('telephone2', models.CharField(blank=True, max_length=20, verbose_name='Téléphone 2')),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('adresse', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vl_od_sphere', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='VL OD Sphère')),
                ('vl_od_cylindre', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='VL OD Cylindre')),
                ('vl_od_axe', models.IntegerField(blank=True, null=True, verbose_name='VL OD Axe (°)')),
                ('vl_od_prisme', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='VL OD Prisme')),
                ('vl_od_base', models.CharField(blank=True, max_length=10, verbose_name='VL OD Base')),
                ('vl_og_sphere', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='VL OG Sphère')),
                ('vl_og_cylindre', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='VL OG Cylindre')),
                ('vl_og_axe', models.IntegerField(blank=True, null=True, verbose_name='VL OG Axe (°)')),
                ('vl_og_prisme', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='VL OG Prisme')),
                ('vl_og_base', models.CharField(blank=True, max_length=10, verbose_name='VL OG Base')),
                ('vp_od_sphere', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='VP OD Sphère')),
                ('vp_od_cylindre', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='VP OD Cylindre')),
                ('vp_od_axe', models.IntegerField(blank=True, null=True, verbose_name='VP OD Axe (°)')),
                ('vp_og_sphere', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='VP OG Sphère')),
                ('vp_og_cylindre', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='VP OG Cylindre')),
                ('vp_og_axe', models.IntegerField(blank=True, null=True, verbose_name='VP OG Axe (°)')),
                ('addition', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Addition')),
                ('ep_vl', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='EP VL (mm)')),
                ('demi_ep_vl_od', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='½EP VL OD (mm)')),
                ('demi_ep_vl_og', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='½EP VL OG (mm)')),
                ('ep_vp', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='EP VP (mm)')),
                ('demi_ep_vp_od', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='½EP VP OD (mm)')),
                ('demi_ep_vp_og', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='½EP VP OG (mm)')),
                ('ordonnance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correction', to='patients.ordonnance')),
            ],
            options={
                'verbose_name': 'Correction',
                'verbose_name_plural': 'Corrections',
            },
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='patients.patient'),
        ),
    ]
