# Generated by Django 6.0.6 on 2026-06-25 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreanceOrganisme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Créance organisme',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrganismePayeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_organisme', models.CharField(choices=[('cnas', 'CNAS'), ('casnos', 'CASNOS'), ('mutuelle', 'Mutuelle / Complémentaire'), ('entreprise', 'Entreprise / Employeur'), ('autre', 'Autre')], default='cnas', max_length=20)),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Code organisme')),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact_nom', models.CharField(blank=True, max_length=150)),
                ('taux_remboursement_montures', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux remb. montures (%)')),
                ('taux_remboursement_verres', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux remb. verres (%)')),
                ('plafond_montures', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Plafond montures (DA)')),
                ('plafond_verres', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Plafond verres (DA)')),
                ('delai_remboursement_jours', models.IntegerField(default=30, verbose_name='Délai remboursement (jours)')),
                ('actif', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Organisme payeur',
                'verbose_name_plural': 'Organismes payeurs',
                'ordering': ['type_organisme', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='CarteChifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_carte', models.CharField(max_length=50, unique=True, verbose_name='N° carte Chifa')),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('taux_remboursement_personnalise', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taux personnalisé (%)')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carte_chifa', to='patients.patient')),
                ('organisme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartes_chifa', to='mutuelles.organismepayeur')),
            ],
            options={
                'verbose_name': 'Carte Chifa',
                'verbose_name_plural': 'Cartes Chifa',
            },
        ),
        migrations.CreateModel(
            name='TiersPayant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', '⏳ En attente de soumission'), ('soumis', "📤 Soumis à l'organisme"), ('partiellement_rembourse', '💰 Partiellement remboursé'), ('rembourse', '✅ Remboursé'), ('rejete', '❌ Rejeté'), ('litige', '⚠ En litige')], default='en_attente', max_length=30)),
                ('montant_total_vente', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_pris_en_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant pris en charge (DA)')),
                ('ticket_moderateur', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ticket modérateur (reste à charge patient)')),
                ('montant_rembourse_reel', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant réellement remboursé')),
                ('numero_bon_prise_en_charge', models.CharField(blank=True, max_length=100)),
                ('date_soumission', models.DateField(blank=True, null=True)),
                ('date_remboursement_prevu', models.DateField(blank=True, null=True)),
                ('date_remboursement_reel', models.DateField(blank=True, null=True)),
                ('motif_rejet', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('carte_chifa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mutuelles.cartechifa')),
                ('organisme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prises_en_charge', to='mutuelles.organismepayeur')),
                ('vente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tiers_payant', to='ventes.vente')),
            ],
            options={
                'verbose_name': 'Tiers-Payant',
                'verbose_name_plural': 'Tiers-Payants',
                'ordering': ['-date_creation'],
            },
        ),
    ]
