# Generated by Django 6.0.6 on 2026-06-25 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atelier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('categorie', models.CharField(choices=[('etui', 'Étui'), ('chaine', 'Chaîne / Cordon'), ('solution', 'Solution entretien'), ('lingette', 'Lingette'), ('tournevis', 'Tournevis / Outils'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('code_barres', models.CharField(blank=True, max_length=50)),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prix_vente', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('stock_minimum', models.IntegerField(default=5)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Accessoire',
                'verbose_name_plural': 'Accessoires',
                'ordering': ['categorie', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Lentille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('type_port', models.CharField(choices=[('journaliere', 'Journalière'), ('bi_hebdo', 'Bi-hebdomadaire'), ('mensuelle', 'Mensuelle'), ('trimestrielle', 'Trimestrielle'), ('annuelle', 'Annuelle'), ('rigide', 'Rigide / Torique')], default='mensuelle', max_length=20)),
                ('puissance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cylindre', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('axe', models.IntegerField(blank=True, null=True)),
                ('addition', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('rayon_courbure', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('diametre', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('numero_lot', models.CharField(blank=True, max_length=100, verbose_name='N° de lot')),
                ('date_limite_consommation', models.DateField(blank=True, null=True, verbose_name='DLC')),
                ('stock', models.IntegerField(default=0)),
                ('stock_minimum', models.IntegerField(default=5)),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prix_vente', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lentille',
                'verbose_name_plural': 'Lentilles',
                'ordering': ['marque', 'reference'],
            },
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='marques/')),
            ],
            options={
                'verbose_name': 'Marque',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Verre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('type_verre', models.CharField(choices=[('unifocal', 'Unifocal'), ('bifocal', 'Bifocal'), ('progressif', 'Progressif'), ('degressif', 'Dégressif')], default='unifocal', max_length=20)),
                ('indice', models.CharField(choices=[('1.50', 'Minéral 1.50'), ('1.56', 'Organique 1.56'), ('1.60', 'Organique 1.60'), ('1.67', 'Organique 1.67'), ('1.74', 'Organique 1.74')], default='1.50', max_length=10)),
                ('traitement', models.CharField(choices=[('standard', 'Standard'), ('ar', 'Anti-reflet'), ('bluecut', 'BlueCut / Anti-lumière bleue'), ('photochromique', 'Photochromique'), ('ar_bluecut', 'Anti-reflet + BlueCut'), ('ar_photo', 'Anti-reflet + Photochromique'), ('polarise', 'Polarisé')], default='standard', max_length=20)),
                ('sphere_min', models.DecimalField(decimal_places=2, default=-10, max_digits=5)),
                ('sphere_max', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('cylindre_max', models.DecimalField(decimal_places=2, default=4, max_digits=4)),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prix_vente', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('stock_minimum', models.IntegerField(default=2)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verres', to='atelier.fournisseur')),
            ],
            options={
                'verbose_name': 'Verre',
                'verbose_name_plural': 'Verres',
                'ordering': ['indice', 'type_verre', 'traitement'],
            },
        ),
        migrations.CreateModel(
            name='Monture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modele', models.CharField(max_length=100, verbose_name='Modèle')),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme'), ('U', 'Unisexe'), ('E', 'Enfant')], default='U', max_length=1)),
                ('couleur', models.CharField(max_length=50)),
                ('taille', models.CharField(blank=True, max_length=20, verbose_name='Taille (ex: 52-18-140)')),
                ('materiau', models.CharField(blank=True, choices=[('acetate', 'Acétate'), ('metal', 'Métal'), ('titane', 'Titane'), ('plastique', 'Plastique'), ('mixte', 'Mixte')], max_length=20)),
                ('code_barres', models.CharField(blank=True, max_length=50, unique=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prix_vente', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('stock_minimum', models.IntegerField(default=1, verbose_name='Stock minimum')),
                ('image', models.ImageField(blank=True, null=True, upload_to='montures/')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='montures', to='stocks.marque')),
            ],
            options={
                'verbose_name': 'Monture',
                'verbose_name_plural': 'Montures',
                'ordering': ['marque', 'modele', 'couleur'],
                'unique_together': {('marque', 'modele', 'couleur', 'taille', 'sexe')},
            },
        ),
    ]
