# Generated by Django 6.0.6 on 2026-06-25 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bon', models.CharField(max_length=30, unique=True)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='bons_commande/')),
                ('envoye_par_email', models.BooleanField(default=False)),
                ('date_envoi_email', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Bon de commande',
                'verbose_name_plural': 'Bons de commande',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('adresse', models.TextField(blank=True)),
                ('contact_nom', models.CharField(blank=True, max_length=150, verbose_name='Nom du contact')),
                ('delai_livraison_jours', models.IntegerField(default=5, verbose_name='Délai livraison (jours)')),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CommandeFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('statut', models.CharField(choices=[('a_commander', '📋 À commander'), ('commande', '📤 Commandé'), ('en_montage', '🔧 En cours de montage'), ('pret', '✅ Prêt pour livraison'), ('livre', '📦 Livré'), ('annule', '❌ Annulé')], default='a_commander', max_length=20)),
                ('priorite', models.CharField(choices=[('normale', 'Normale'), ('urgente', 'Urgente'), ('tres_urgente', 'Très urgente')], default='normale', max_length=20)),
                ('description', models.TextField(blank=True, verbose_name='Description / Détails du verre')),
                ('notes_atelier', models.TextField(blank=True)),
                ('date_commande', models.DateField(blank=True, null=True, verbose_name='Date de commande')),
                ('date_livraison_prevue', models.DateField(blank=True, null=True, verbose_name='Date livraison prévue')),
                ('date_livraison_reelle', models.DateField(blank=True, null=True, verbose_name='Date livraison réelle')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_atelier', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Commande Fournisseur',
                'verbose_name_plural': 'Commandes Fournisseurs',
                'ordering': ['-date_creation'],
            },
        ),
    ]
