# Generated by Django 6.0.6 on 2026-06-25 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atelier', '0001_initial'),
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandefournisseur',
            name='vente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_atelier', to='ventes.vente'),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons', to='atelier.commandefournisseur'),
        ),
        migrations.AddField(
            model_name='commandefournisseur',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='atelier.fournisseur'),
        ),
    ]
