# Generated by Django 6.0.6 on 2026-06-28 14:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commandefournisseur',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Commande Atelier', 'verbose_name_plural': 'Commandes Atelier'},
        ),
        migrations.AlterField(
            model_name='commandefournisseur',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_atelier', to='atelier.fournisseur'),
        ),
        migrations.AlterField(
            model_name='commandefournisseur',
            name='statut',
            field=models.CharField(choices=[('a_commander', '📋 À préparer'), ('commande', '📤 En cours'), ('en_montage', '🔧 En cours de montage'), ('pret', '✅ Prêt pour livraison'), ('livre', '📦 Livré'), ('annule', '❌ Annulé')], default='a_commander', max_length=20),
        ),
        migrations.CreateModel(
            name='AchatFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('statut', models.CharField(choices=[('brouillon', '📝 Brouillon'), ('en_attente', '⏳ En attente de réception'), ('recu', '✅ Reçu'), ('annule', '❌ Annulé')], default='brouillon', max_length=20)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('date_commande', models.DateField(default=django.utils.timezone.now)),
                ('date_reception', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achats', to='atelier.fournisseur')),
            ],
            options={
                'verbose_name': 'Achat Fournisseur',
                'verbose_name_plural': 'Achats Fournisseurs',
                'ordering': ['-date_creation'],
            },
        ),
    ]
